(require "lisp/common")
(require "lisp/wd")

(defun envelope-soft-full-kick (data)
  (set 'duration wd-full-note-duration)
  (set 'attack (/ duration 16))
  (set 'decay (/ duration 4))
  (set 'sustain 0.5)
  (set 'release (/ duration 2))
  (wd-adsr attack decay sustain release data))
;(wd-plot (envelope-soft-full-kick (wd-from-frequencies (wd-spline (list (cons 0.0 d3) (cons 2.5 d2) (cons 10.0 0.0) ) wd-full-note-duration))))
(wd-plot (wd-spline (list (cons 0.0 d3) (cons 2.5 d2) (cons 10.0 0.0) ) wd-full-note-duration))
